# Generated by Django 4.2.9 on 2026-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("EXAM", "Exam"), ("MATERIAL", "Material")],
                        default="EXAM",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("subject", models.CharField(max_length=120)),
                ("teacher", models.CharField(blank=True, max_length=120)),
                (
                    "program",
                    models.CharField(
                        blank=True,
                        choices=[("BM", "BM"), ("LEHRE", "Lehre")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("file", models.FileField(upload_to="content/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
