# Generated by Django 4.2.9 on 2026-01-08 15:06
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("exams", "0002_uploadbatch_uploadfile")]
    operations = [
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("slug", models.SlugField(max_length=140, unique=True)), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0))], options={"ordering": ("sort_order", "name")}),
        migrations.AddField(model_name="uploadbatch", name="content_type", field=models.CharField(choices=[("EXAM", "Exam"), ("MATERIAL", "Material")], default="EXAM", max_length=20)),
        migrations.AddField(model_name="uploadbatch", name="status", field=models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
        migrations.AddField(model_name="uploadbatch", name="token", field=models.UUIDField(default=uuid.uuid4, editable=False)),
        migrations.AddField(model_name="uploadfile", name="content_type", field=models.CharField(choices=[("EXAM", "Exam"), ("MATERIAL", "Material")], default="EXAM", max_length=20)),
        migrations.AlterField(model_name="uploadbatch", name="owner", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="upload_batches", to=settings.AUTH_USER_MODEL)),
        migrations.CreateModel(name="SubCategory", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("slug", models.SlugField(max_length=140)), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0)), ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subcategories", to="exams.category"))], options={"ordering": ("sort_order", "name"), "unique_together": {("category", "slug")}}),
        migrations.AddField(model_name="uploadbatch", name="category", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="upload_batches", to="exams.category")),
        migrations.AddField(model_name="uploadbatch", name="subcategory", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="upload_batches", to="exams.subcategory")),
        migrations.AddField(model_name="uploadfile", name="category", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="upload_files", to="exams.category")),
        migrations.AddField(model_name="uploadfile", name="subcategory", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="upload_files", to="exams.subcategory")),
    ]
